#!/usr/bin/env bash
# Install runtime configuration for the userspace apt/dpkg and seed the dpkg
# database from the system so apt treats already-installed libraries as
# satisfied (and only installs the leaf packages you ask for).
#
# Called by scripts/setup/install-config.sh; not usually run directly. Re-running
# is safe. Options:
#   --reseed      refresh the seeded status from the system
#   --no-shell    do not touch ~/.bashrc / ~/.profile
source "$(dirname "${BASH_SOURCE[0]}")/../scripts/common.sh"

RESEED=0
SHELL_PATH=1
for arg in "$@"; do
  case "$arg" in
    --reseed)   RESEED=1 ;;
    --no-shell) SHELL_PATH=0 ;;
  esac
done

log "prefix: $PREFIX"

mkdir -p "$PREFIX/etc/apt/sources.list.d" "$PREFIX/etc/apt/apt.conf.d" \
         "$PREFIX/etc/dpkg/dpkg.cfg.d" \
         "$PREFIX/etc/apt/preferences.d" \
         "$PREFIX/var/lib/apt/lists/partial" \
         "$PREFIX/var/cache/apt/archives/partial" \
         "$PREFIX/var/lib/dpkg"/{info,updates,triggers,alternatives} \
         "$PREFIX/var/log/apt"

# The host's Debian suite: the first one its sources name for the Debian
# archive (not -security or -updates), else its codename. A newer suite than
# the host's (sid on a testing host) brings packages built against newer
# libraries than the host has, which sudo-less never upgrades.
host_suite() {
  local f s
  for f in /etc/apt/sources.list /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
    [ -r "$f" ] || continue
    case $f in
      *.sources) s=$(awk '/^URIs:/ { d = ($0 ~ /\/debian\/?([[:space:]]|$)/) }
                         /^Suites:/ && d { print $2; exit }' "$f") ;;
      *) s=$(awk '$1 == "deb" { for (i = 2; i <= NF; i++) if ($i !~ /^\[/ && $i !~ /\]$/) break
                                if ($i ~ /\/debian\/?$/) { print $(i + 1); exit } }' "$f") ;;
    esac
    case $s in ''|*-security|*-updates|*-backports|*-proposed-updates) ;; *) echo "$s"; return ;; esac
  done
  s=$(sed -n 's/^VERSION_CODENAME=//p' /etc/os-release 2>/dev/null)
  echo "${s:-sid}"
}
SRC=$PREFIX/etc/apt/sources.list
# Written once, or again while it is still one sudo-less wrote (the sid of
# earlier versions included); a sources.list you changed is left alone.
if [ ! -e "$SRC" ] || grep -q '^# Generated by sudo-less' "$SRC" ||
   [ "$(cat "$SRC")" = "deb [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://deb.debian.org/debian sid main" ]; then
  suite=$(host_suite)
  sed "s|@SUITE@|$suite|g" "$REPO/apt-dpkg/config/sources.list.in" > "$SRC"
  chmod 0644 "$SRC"
  log "apt sources: Debian $suite, as the host"
fi
# generate the dpkg/apt prefix config from the template, so the prefix is not
# hardcoded (see apt-dpkg/config/apt.conf.d/00local-prefix.in)
sed "s|@PREFIX@|$PREFIX|g" "$REPO/apt-dpkg/config/apt.conf.d/00local-prefix.in" \
  > "$PREFIX/etc/apt/apt.conf.d/00local-prefix"
chmod 0644 "$PREFIX/etc/apt/apt.conf.d/00local-prefix"
sed "s|@PREFIX@|$PREFIX|g" "$REPO/apt-dpkg/config/dpkg/dpkg.cfg.in" > "$PREFIX/etc/dpkg/dpkg.cfg"
chmod 0644 "$PREFIX/etc/dpkg/dpkg.cfg"

# sudo-less's tools, the dpkg wrappers and the apt hooks that call them
# (prefix-check before dpkg runs, prefix-integrate after): tools/install.sh.
PREFIX=$PREFIX bash "$REPO/tools/install.sh"

# apt verifies signatures with the host's sqv (Debian's default verifier)
if ! command -v sqv >/dev/null; then
  log "note: sqv not found on PATH; apt-get update cannot verify signatures"
  log "      install it, e.g.: extract the 'sqv' .deb into $PREFIX"
fi

STATUS="$PREFIX/var/lib/dpkg/status"
mkdir -p "$PREFIX/.sl/state"
MINE="$PREFIX/.sl/state/reseed-mine.status"
rm -f "$MINE"
if [ "$RESEED" = 1 ] && [ -s "$STATUS" ]; then
  # A reseed replaces the *seeded* (system) entries with the host's current
  # ones, so a package the host removed (or never had there) stops being
  # reported as installed — that is the point of reseeding. But the status
  # file is one flat list, with no tag telling "seeded" from "yours" apart,
  # so a plain `cp` over it would just as well drop every package you
  # installed into the prefix yourself (#30: "--reseed drops packages").
  # Tell them apart the same way lock-seeded.sh does: yours are the ones
  # NOT on hold (seeded packages are held after every run, below) — pull
  # their stanzas out first, to add back once the host's copy is in place.
  DPKG="$PREFIX/.sl/dpkg/bin/dpkg"
  [ -x "$DPKG" ] ||
    die "reseed: no dpkg at $DPKG (a broken prefix?); refusing, to avoid dropping your packages blind"
  NAMES="$PREFIX/.sl/state/reseed-mine.pkgs"
  "$DPKG" --admindir="$PREFIX/var/lib/dpkg" --get-selections |
    awk '$2 != "hold" { sub(/:.*$/, "", $1); print $1 }' > "$NAMES"
  awk -v f="$NAMES" '
    BEGIN { while ((getline p < f) > 0) want[p] = 1 }
    /^Package: / { keep = ($2 in want) }
    keep { print }
  ' "$STATUS" > "$MINE"
  rm -f "$NAMES"
fi
if [ "$RESEED" = 1 ] || [ ! -s "$STATUS" ]; then
  log "seeding dpkg status from /var/lib/dpkg/status"
  cp /var/lib/dpkg/status "$STATUS"
  # copy the system's control-file lists so dpkg doesn't warn that seeded
  # packages are "missing the list control file" / md5sums
  cp -n /var/lib/dpkg/info/*.list "$PREFIX/var/lib/dpkg/info/" 2>/dev/null || true
  cp -n /var/lib/dpkg/info/*.md5sums "$PREFIX/var/lib/dpkg/info/" 2>/dev/null || true
  cp -n /var/lib/dpkg/info/*.conffiles "$PREFIX/var/lib/dpkg/info/" 2>/dev/null || true
fi
if [ -s "$MINE" ]; then
  # Add the preserved stanzas back, skipping any package the host's fresh
  # copy already has (its entry there is the newer one).
  ADD="$PREFIX/.sl/state/reseed-add.status"
  awk -v f="$STATUS" '
    BEGIN { while ((getline l < f) > 0) if (l ~ /^Package: /) { split(l, a, " "); have[a[2]] = 1 } }
    /^Package: / { keep = !($2 in have) }
    keep { print }
  ' "$MINE" > "$ADD"
  if [ -s "$ADD" ]; then
    n=$(grep -c '^Package: ' "$ADD")
    printf '\n' >> "$STATUS"
    cat "$ADD" >> "$STATUS"
    log "reseed: kept $n of your own packages"
  fi
  rm -f "$ADD"
fi
rm -f "$MINE"
# In the view the host's /etc/alternatives shows through, so the prefix's
# database starts with the host's alternatives.
cp -n /var/lib/dpkg/alternatives/* "$PREFIX/var/lib/dpkg/alternatives/" 2>/dev/null || true
# dpkg appends to /var/log/dpkg.log, and in the view a host file cannot be
# written in place: the prefix has its own.
mkdir -p "$PREFIX/var/log"
[ -e "$PREFIX/var/log/dpkg.log" ] || : > "$PREFIX/var/log/dpkg.log"

# Protect the seeded (system) packages: hold them so apt cannot accidentally
# upgrade/remove them into/from the prefix. Our own installs stay upgradable.
bash "$REPO/scripts/setup/lock-seeded.sh" lock

# Make installed packages runnable in new shells (unless opted out).
if [ "$SHELL_PATH" = 1 ]; then
  bash "$REPO/scripts/setup/install-shell-path.sh"
  bash "$REPO/scripts/setup/install-session-env.sh"
else
  log "skipping shell PATH setup (--no-shell). Add manually:"
  printf '  export PATH="%s/sbin:%s/bin:%s/usr/bin:$PATH"\n' "$PREFIX" "$PREFIX" "$PREFIX"
fi
