#!/usr/bin/env bash
# Regenerate tools/syscalls/ARCH: the syscall numbers prefix-sandbox builds
# its seccomp filters with (one "NAME NUMBER" per line, for each syscall the
# architecture has).
#
#   dev/syscall-tables.sh
#
# The names: the kernel headers' (linux-libc-dev) and every name in
# systemd's syscall groups. The numbers: libseccomp's scmp_sys_resolver
# (package seccomp; `apt install seccomp` into the prefix is enough). Run it
# when a new kernel adds syscalls, and commit the result.
set -eu
REPO=$(cd "$(dirname "$0")/.." && pwd)
R=$(command -v scmp_sys_resolver || echo "${PREFIX:-$HOME/.local}/usr/bin/scmp_sys_resolver")
[ -x "$R" ] || { echo "scmp_sys_resolver not found (apt install seccomp)" >&2; exit 1; }

names=$(
  {
    grep -hoE '^#define __NR3?2?_[a-z0-9_]+' /usr/include/*/asm/unistd_64.h \
      /usr/include/asm-generic/unistd.h 2>/dev/null | sed -E 's/^#define __NR3?2?_//'
    systemd-analyze syscall-filter --no-pager 2>/dev/null |
      sed -nE 's/^    ([a-z0-9_]+)$/\1/p'
  } | grep -vE '^(syscalls|arch_specific_syscall)$' | LC_ALL=C sort -u)

for arch in x86_64 aarch64; do
  out=$REPO/tools/syscalls/$arch
  {
    echo "# $arch syscall numbers for prefix-sandbox; generated by dev/syscall-tables.sh"
    for n in $names; do
      nr=$("$R" -a "$arch" "$n" 2>/dev/null) || continue
      [ "${nr#-}" = "$nr" ] && echo "$n $nr"
    done
  } > "$out.new"
  mv "$out.new" "$out"
  echo "$out: $(($(wc -l < "$out") - 1)) syscalls"
done
