#!/usr/bin/env bash
# Add the userspace apt/dpkg prefix dirs to the shell PATH, idempotently, so
# packages installed into $PREFIX/usr/bin are runnable in new shells. Also puts
# $PREFIX/usr/share on XDG_DATA_DIRS: a session started from a login shell
# (Phosh, GNOME) takes it from here, so prefix apps show up in the launcher.
#
#   ./scripts/setup/install-shell-path.sh
#
# No APT_CONFIG here: it would point the system's apt at the prefix too. The
# sl-* commands set it for their own run (tools/sl.sh).
#
# Without this, `sl-install foo` puts the binary in $PREFIX/usr/bin but a
# fresh terminal can't find it. The settings are a file in the prefix,
# $PREFIX/.sudo-less/session/shell.sh (where a package's install scripts
# cannot write); ~/.bashrc and ~/.profile get a marked block of one line
# that reads it if it is there, so removing the prefix breaks no shell.
# Re-running refreshes both. Called automatically by install-config.sh
# (skip with --no-shell).
set -euo pipefail
source "$(dirname "$0")/../common.sh"

MARK="# >>> sudo-less PATH >>>"
END="# <<< sudo-less PATH <<<"

SHELL_SH=$PREFIX/.sudo-less/session/shell.sh
mkdir -p "${SHELL_SH%/*}"
cat > "$SHELL_SH" <<EOF
# Generated by sudo-less (see $REPO) — do not edit by hand. Read by the
# line in ~/.bashrc and ~/.profile, in sh as well as bash.
if [ -d "$PREFIX/bin" ] || [ -d "$PREFIX/usr/bin" ]; then
    case ":\$PATH:" in
        *":$PREFIX/usr/bin:"*) ;;
        *) PATH="$PREFIX/sbin:$PREFIX/bin:$PREFIX/usr/bin:\$PATH"
           # your own programs stay in front of the prefix's
           [ ! -d "\$HOME/.local/bin" ] || PATH="\$HOME/.local/bin:\$PATH" ;;
    esac
fi
export PATH
# desktop launchers and icons: Phosh/GNOME take XDG_DATA_DIRS from the login
# shell and push it into systemd --user, overriding environment.d
case ":\${XDG_DATA_DIRS:=/usr/local/share:/usr/share}:" in
    *":$PREFIX/usr/share:"*) ;;
    *) XDG_DATA_DIRS="$PREFIX/usr/share:$PREFIX/share:\$XDG_DATA_DIRS" ;;
esac
export XDG_DATA_DIRS
EOF

read -r -d '' BLOCK <<EOF || true
$MARK
[ ! -r "$SHELL_SH" ] || . "$SHELL_SH"
$END
EOF

# an account created without /etc/skel has neither file: create ~/.profile,
# or nothing would put the prefix on PATH (and nothing would say so)
[ -e "$HOME/.bashrc" ] || [ -e "$HOME/.profile" ] || : > "$HOME/.profile"

updated=0
for rc in "$HOME/.bashrc" "$HOME/.profile"; do
  [ -e "$rc" ] || continue
  if grep -qF "$MARK" "$rc"; then
    # Replace the block in place. Earlier versions deleted it and appended a
    # new one after a blank line, so every refresh left one more blank line
    # behind; squeeze the blank lines in front of the block back to one.
    BLOCK="$BLOCK" MARK="$MARK" END="$END" awk '
      skip { if ($0 == ENVIRON["END"]) skip = 0; next }
      /^$/ { blanks++; next }
      $0 == ENVIRON["MARK"] { if (blanks) print ""; blanks = 0
                              print ENVIRON["BLOCK"]; skip = 1; next }
      { for (; blanks > 0; blanks--) print ""; print }
      END { for (; blanks > 0; blanks--) print "" }' "$rc" > "$rc.sudo-less.tmp"
    cat "$rc.sudo-less.tmp" > "$rc"    # keep the file's inode and mode
    rm -f "$rc.sudo-less.tmp"
    log "refreshed $rc"
  else
    printf '\n%s\n' "$BLOCK" >> "$rc"
    log "updated $rc"
  fi
  updated=$((updated + 1))
done

[ "$updated" -gt 0 ] && log "open a new login shell (or source the file above) to pick it up"
log "prefix dirs: $PREFIX/sbin, $PREFIX/bin, $PREFIX/usr/bin"
