#!/usr/bin/env bash
# Make the prefix visible to the *desktop session* (Phosh/GNOME), not just the
# shell, so GUI apps installed with the userspace apt appear in the launcher.
#
#   ./scripts/setup/install-session-env.sh
#
# Writes ~/.config/environment.d/50-sudo-less.conf, which systemd --user reads
# when the session starts, and a user unit that starts the run view at login.
# Both are files in the prefix ($PREFIX/.sl/state/session, where a
# package's install scripts cannot write), with a link to each where
# systemd looks. ~/.config/sudo-less becomes a link to $PREFIX/.sl/config, your
# own settings (the services' sandboxes: tools/prefix-sandbox.sh). Values
# are literal (no shell expansion), so the prefix is baked in. Re-login
# (restart the session) to apply.
#
# Without this, `.desktop` files installed to $PREFIX/usr/share/applications
# are never scanned: Phosh discovers launchers via $XDG_DATA_DIRS. This covers
# systemd --user services. A session that starts from a login shell (Phosh via
# gnome-session) then pushes the shell's XDG_DATA_DIRS into systemd --user and
# overrides this value, so install-shell-path.sh sets it in ~/.profile as well.
set -euo pipefail
source "$(dirname "$0")/../common.sh"

S=$PREFIX/.sl/state/session
CONF=${XDG_CONFIG_HOME:-$HOME/.config}
mkdir -p "$S" "$CONF/environment.d" "$CONF/systemd/user/default.target.wants"

# put LINK TARGET: LINK points to TARGET (an earlier version wrote a file there)
put() { ln -sfn "$2" "$1"; log "linked $1"; }

# ~/.local/bin, your own programs, stays in front of the prefix's.
cat > "$S/50-sudo-less.conf" <<EOF
# Generated by sudo-less (see $REPO) — do not edit by hand.
# Session PATH and data dirs so prefix-installed apps work and show up in the
# desktop launcher (Phosh/GNOME).
PATH=$HOME/.local/bin:$PREFIX/.sl/sbin:$PREFIX/.sl/bin:$PREFIX/usr/bin:/usr/local/bin:/usr/bin:/bin
XDG_DATA_DIRS=$PREFIX/usr/share:/usr/local/share:/usr/share
EOF
put "$CONF/environment.d/50-sudo-less.conf" "$S/50-sudo-less.conf"

# Start the shared run view (tools/prefix-view.sh --run) at login, so the
# first wrapped program does not pay for building it. Without this it is
# started on first use. Enabled by hand (the symlink `systemctl --user enable`
# would make), so this does not need the user manager.
cat > "$S/sudo-less-run-view.service" <<EOF
# Generated by sudo-less (see $REPO) — do not edit by hand.
[Unit]
Description=sudo-less run view for programs installed in $PREFIX

[Service]
Type=oneshot
RemainAfterExit=yes
Environment=PREFIX=$PREFIX
ExecStart=$PREFIX/.sl/lib/prefix-view --start
ExecStop=$PREFIX/.sl/lib/prefix-view --stop

[Install]
WantedBy=default.target
EOF
put "$CONF/systemd/user/sudo-less-run-view.service" "$S/sudo-less-run-view.service"
ln -sfn ../sudo-less-run-view.service \
  "$CONF/systemd/user/default.target.wants/sudo-less-run-view.service"
log "the run view starts at next login"

# Your settings: in the prefix, and found where settings usually are. An
# earlier version kept them in ~/.config/sudo-less itself: they move in.
mkdir -p "$PREFIX/.sl/config"
if [ -d "$CONF/sudo-less" ] && [ ! -L "$CONF/sudo-less" ]; then
  cp -a "$CONF/sudo-less/." "$PREFIX/.sl/config/"
  rm -rf "$CONF/sudo-less"
  log "moved $CONF/sudo-less into $PREFIX/.sl/config"
fi
put "$CONF/sudo-less" "$PREFIX/.sl/config"
log "re-login (restart the session) for Phosh/GNOME to pick it up"
