#!/usr/bin/env bash
# Make the prefix visible to the *desktop session* (Phosh/GNOME), not just the
# shell, so GUI apps installed with the userspace apt appear in the launcher.
#
#   ./scripts/setup/install-session-env.sh
#
# Writes ~/.config/environment.d/50-sudo-less.conf, which systemd --user reads
# when the session starts, and a user unit that starts the run view at login. Values are literal (no shell expansion), so the
# prefix is baked in. Re-login (restart the session) to apply.
#
# Without this, `.desktop` files installed to $PREFIX/usr/share/applications
# are never scanned: Phosh discovers launchers via $XDG_DATA_DIRS, which a
# shell rc cannot change for the session.
set -euo pipefail
source "$(dirname "$0")/../common.sh"

DEST="${XDG_CONFIG_HOME:-$HOME/.config}/environment.d/50-sudo-less.conf"
mkdir -p "$(dirname "$DEST")"

cat > "$DEST" <<EOF
# Generated by sudo-less (see $REPO) — do not edit by hand.
# Session PATH and data dirs so prefix-installed apps work and show up in the
# desktop launcher (Phosh/GNOME).
PATH=$PREFIX/sbin:$PREFIX/bin:$PREFIX/usr/bin:/usr/local/bin:/usr/bin:/bin
XDG_DATA_DIRS=$PREFIX/usr/share:$PREFIX/share:/usr/local/share:/usr/share
EOF

log "wrote $DEST"

# Start the shared run view (tools/prefix-view.sh --run) at login, so the
# first wrapped program does not pay for building it. Without this it is
# started on first use. Enabled by hand (the symlink `systemctl --user enable`
# would make), so this does not need the user manager.
UNITS="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
mkdir -p "$UNITS/default.target.wants"
cat > "$UNITS/sudo-less-run-view.service" <<EOF
# Generated by sudo-less (see $REPO) — do not edit by hand.
[Unit]
Description=sudo-less run view for programs installed in $PREFIX

[Service]
Type=oneshot
RemainAfterExit=yes
Environment=PREFIX=$PREFIX
ExecStart=$PREFIX/lib/sudo-less/prefix-view --start
ExecStop=$PREFIX/lib/sudo-less/prefix-view --stop

[Install]
WantedBy=default.target
EOF
ln -sfn ../sudo-less-run-view.service \
  "$UNITS/default.target.wants/sudo-less-run-view.service"
log "wrote $UNITS/sudo-less-run-view.service (starts at next login)"
log "re-login (restart the session) for Phosh/GNOME to pick it up"
