#!/bin/bash
# deb2home — install Debian packages into $HOME without root.
#
# Usage: deb2home [options] PKG [PKG...]
#   -d, --dir DIR    extract prefix (default: ~/.local/opt)
#   -b, --bin DIR    link/wrapper dir (default: ~/.local/bin)
#   -n, --no-deps    do not fetch missing dependencies
#   -N, --dry-run    show what would be done
#   -l, --list       list installed prefixes and exit
#   -h, --help       show this help
#
# Resolves missing Depends/PreDepends with apt-cache, downloads every needed
# .deb with apt-get download, extracts it under <prefix>/<pkg> with dpkg -x,
# then links each binary into <bin> (symlink, or a wrapper that sets
# LD_LIBRARY_PATH/XDG_DATA_DIRS when the package ships its own libs).
#
# Not a full apt: no postinst scripts, maintainer scripts, conffiles,
# alternatives, or dpkg database. Packages needing those may not work.
#
# Env: DEB2HOME_PREFIX, DEB2HOME_BIN
set -euo pipefail

OPT="${DEB2HOME_PREFIX:-$HOME/.local/opt}"
BIN="${DEB2HOME_BIN:-$HOME/.local/bin}"
WITH_DEPS=1
DRY=0

usage() {
  sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

list_prefixes() {
  shopt -s nullglob
  local d
  for d in "$OPT"/*/; do printf '%s\n' "${d%/}"; done
}

pkgs=()
while [ $# -gt 0 ]; do
  case "$1" in
    -d|--dir)     OPT="$2"; shift 2;;
    -b|--bin)     BIN="$2"; shift 2;;
    -n|--no-deps) WITH_DEPS=0; shift;;
    -N|--dry-run) DRY=1; shift;;
    -l|--list)    list_prefixes; exit 0;;
    -h|--help)    usage 0;;
    -*) echo "deb2home: unknown option: $1" >&2; usage 1;;
    *)  pkgs+=("$1"); shift;;
  esac
done
[ "${#pkgs[@]}" -gt 0 ] || usage 1

run() { if [ "$DRY" -eq 1 ]; then echo "  [dry] $*"; else "$@"; fi; }

is_installed() { [ "$(dpkg-query -W -f='${db:Status-Abbrev}' "$1" 2>/dev/null || true)" = "ii " ]; }

# Sonames a binary cannot resolve under the current LIBPATH. Uses the dynamic
# loader in trace mode, so unlike ldd it never executes the (possibly
# untrusted, freshly downloaded) binary.
missing_libs() {
  local f="$1" interp
  interp="$(readelf -l "$f" 2>/dev/null \
    | awk '/program interpreter/{gsub(/[][]/,"",$NF); print $NF; exit}')"
  [ -n "$interp" ] && [ -x "$interp" ] || return 0
  LD_TRACE_LOADED_OBJECTS=1 \
    LD_LIBRARY_PATH="$LIBPATH${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
    "$interp" "$f" 2>/dev/null | awk '/not found/{print $1}'
}

resolve_missing_deps() {
  local pkg
  {
    for pkg in "$@"; do
      apt-cache depends --recurse --no-recommends --no-suggests \
        --no-conflicts --no-breaks --no-replaces --no-enhances "$pkg" 2>/dev/null
    done
  } | sed -n 's/.*Depends: *//p' | awk '{print $1}' | tr -d '<>' \
    | sed 's/:[a-z0-9]*$//' | sort -u
}

# --- work out the full package set -----------------------------------------
want=()
for pkg in "${pkgs[@]}"; do
  if is_installed "$pkg"; then
    echo "==> $pkg: already installed system-wide (extracting anyway)"
  fi
  want+=("$pkg")
done

if [ "$WITH_DEPS" -eq 1 ]; then
  echo "==> resolving dependencies"
  while read -r dep; do
    [ -n "$dep" ] || continue
    is_installed "$dep" && continue
    apt-cache show "$dep" 2>/dev/null | grep -q '^Filename:' || continue
    case " ${want[*]} " in *" $dep "*) continue;; esac
    want+=("$dep")
    echo "    + $dep"
  done < <(resolve_missing_deps "${pkgs[@]}")
fi

echo "==> packages: ${want[*]}"
[ "$DRY" -eq 1 ] && { echo "==> dry run, nothing changed"; exit 0; }

mkdir -p "$OPT" "$BIN"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
cd "$tmp"

echo "==> downloading"
dl_failed=0
for p in "${want[@]}"; do
  if ! apt-get download "$p" >/dev/null 2>&1; then
    echo "  !! failed to download: $p" >&2
    dl_failed=$((dl_failed+1))
  fi
done
if [ "$dl_failed" -gt 0 ]; then
  echo "==> $dl_failed package(s) failed to download; aborting" >&2
  exit 1
fi

shopt -s nullglob
echo "==> extracting"
for d in *.deb; do
  n="${d%%_*}"
  rm -rf "$OPT/$n"
  dpkg -x "$d" "$OPT/$n"
  echo "    $n -> $OPT/$n"
done

# library + data search paths from everything we just extracted
libdirs=(); datadirs=()
for d in "$OPT"/*/usr/lib/*/ "$OPT"/*/usr/lib/ "$OPT"/*/lib/*/ "$OPT"/*/lib/; do
  [ -d "$d" ] && libdirs+=("${d%/}")
done
for d in "$OPT"/*/usr/share/; do
  [ -d "$d" ] && datadirs+=("${d%/}")
done
LIBPATH="$(IFS=:; echo "${libdirs[*]:-}")"
DATAPATH="$(IFS=:; echo "${datadirs[*]:-}")"

echo "==> linking binaries"
linked=0; wrapped=0
for d in "$OPT"/*/; do
  p="${d%/}"; p="${p##*/}"
  for sub in usr/bin usr/games usr/sbin; do
    for f in "$OPT/$p/$sub/"*; do
      [ -f "$f" ] && [ -x "$f" ] || continue
      name="$(basename "$f")"
      missing="$(missing_libs "$f" || true)"
      if [ -z "$missing" ]; then
        ln -sf "$f" "$BIN/$name"
        linked=$((linked+1))
      else
        {
          echo '#!/bin/sh'
          echo "# generated by deb2home for $name"
          [ -n "$LIBPATH" ] && echo "export LD_LIBRARY_PATH=\"$LIBPATH\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}\""
          [ -n "$DATAPATH" ] && echo "export XDG_DATA_DIRS=\"$DATAPATH\${XDG_DATA_DIRS:+:\$XDG_DATA_DIRS}\""
          echo "exec \"$f\" \"\$@\""
        } > "$BIN/$name"
        chmod 0755 "$BIN/$name"
        wrapped=$((wrapped+1))
        echo "    wrap $name (needs: $missing)"
      fi
    done
  done
done

echo "==> done: $linked linked, $wrapped wrapped in $BIN"
